"""Hybrid Pipeline — implements the Trade Quality Classifier workflow to filter strategy signals."""

from __future__ import annotations

import logging
import os
from typing import Any

import numpy as np
import pandas as pd

from quant_engine.ml.datasets.builder import DatasetBuilder
from quant_engine.ml.explainability.explainer import ExplainabilityEngine
from quant_engine.ml.metrics.evaluation import calculate_classification_metrics
from quant_engine.ml.models.adapters import get_model_adapter
from quant_engine.ml.persistence.registry import ModelRegistry
from quant_engine.ml.tuning.tuner import OptunaTuner

logger = logging.getLogger(__name__)


class HybridPipeline:
    """Trains an ML model to evaluate and filter trade candidates generated by rule-based strategies."""

    def __init__(self, config: dict[str, Any]) -> None:
        """Initialize the HybridPipeline.

        Args:
            config: Full research configuration dict.
        """
        self.config = config
        self.ml_config = config.get("machine_learning", {})

        # Force dataset and label config properties to align with meta-labeling requirements
        self.feature_config = self.ml_config.get("dataset", {}).copy()
        self.feature_config["source"] = "generated_trades"

        self.label_config = self.ml_config.get("labels", {}).copy()
        self.label_config["type"] = "meta_labeling"
        # Use return threshold, default to 0.0 (any profitable trade is success)
        if "threshold" not in self.label_config:
            self.label_config["threshold"] = 0.0

        self.dataset_builder = DatasetBuilder(
            feature_config=self.feature_config,
            label_config=self.label_config,
        )

        self.tuner = OptunaTuner(self.ml_config.get("tuning", {}))
        self.explainer = ExplainabilityEngine(self.ml_config.get("explainability", {}))
        self.registry = ModelRegistry(
            os.path.join(self.config.get("output", {}).get("base_dir", "./data/runs"), "models")
        )
        self.confidence_threshold = float(
            self.ml_config.get("deployment", {}).get("confidence_threshold", 0.80)
        )

    def run_hybrid_filtering(
        self,
        strategy_id: str,
        df: pd.DataFrame,
        trades: list[dict[str, Any]],
        model_name: str,
        run_id: str,
        version: str = "v1.0",
    ) -> dict[str, Any]:
        """Execute the Hybrid ML Trade Quality Classifier pipeline.

        Trains the classifier on trade candidates, filters out low-confidence trades,
        and computes the metrics comparison.

        Args:
            strategy_id: Identifier of the primary rule-based strategy.
            df: Raw OHLCV DataFrame.
            trades: List of trade candidate dicts generated by standard backtester.
            model_name: Name of the model adapter to use.
            run_id: Active research run ID.
            version: Model version tag.

        Returns:
            Dictionary comparing original vs. hybrid strategy metrics.
        """
        logger.info(
            f"Running Hybrid ML filtering for strategy '{strategy_id}' under run '{run_id}'..."
        )

        if not trades or len(trades) < 15:
            logger.warning(
                f"Strategy {strategy_id} has too few trades ({len(trades) if trades else 0}) to train a Trade Quality Classifier. Min required: 15."
            )
            return {}

        # 1. Build dataset (meta-labeling: only rows where strategy entries occurred)
        X, y = self.dataset_builder.build_dataset(df, trades=trades)
        if len(X) < 10:
            logger.warning(
                f"Meta-labeled dataset size is too small ({len(X)}) after cleaning. Skipping strategy '{strategy_id}'."
            )
            return {}

        # 2. Chronological chronological split (e.g. 70% train, 30% test)
        n_samples = len(X)
        split_idx = int(n_samples * 0.7)

        X_train, y_train = X.iloc[:split_idx], y.iloc[:split_idx]
        X_test, y_test = X.iloc[split_idx:], y.iloc[split_idx:]

        if len(X_train) < 8 or len(X_test) < 3:
            logger.warning(
                f"Chronological split produced insufficient samples for train ({len(X_train)}) or test ({len(X_test)}). Skipping strategy."
            )
            return {}

        # 3. Hyperparameter tuning (if enabled)
        params = {}
        if self.ml_config.get("tuning", {}).get("enabled", False):
            try:
                # Use TimeSeriesSplit tuning
                params = self.tuner.tune(model_name, X_train, y_train, is_classifier=True)
            except Exception as e:
                logger.error(
                    f"Optuna tuning failed for Trade Quality Classifier. Falling back to default params. Error: {e}"
                )

        # 4. Train final classifier on training set
        model_config = {
            "is_classifier": True,
            "params": params,
        }
        adapter = get_model_adapter(model_name, model_config)
        adapter.train(X_train, y_train)

        # 5. Predict probabilities (confidence) on test set
        # predict_proba returns [prob_class_0, prob_class_1]
        probs = adapter.predict_proba(X_test)[:, 1]
        preds_filtered = (probs >= self.confidence_threshold).astype(int)

        # Evaluate ML classification performance on test set
        ml_metrics = calculate_classification_metrics(y_test, (probs >= 0.5).astype(int))
        logger.info(f"Classifier test performance (threshold=0.5): {ml_metrics}")

        # 6. Apply filtering to actual trades
        # Map X_test timestamps back to the original trades list
        test_timestamps = set(X_test.index)

        # Build lookup for confidence scores by timestamp
        prob_lookup = {ts: prob for ts, prob in zip(X_test.index, probs)}

        original_test_trades = []
        hybrid_test_trades = []

        # We normalize trade times to compare with pandas datetime indexes
        for trade in trades:
            entry_time = pd.to_datetime(trade.get("entry_time"))
            if df.index.tz is not None and entry_time.tz is None:
                entry_time = entry_time.tz_localize("UTC")
            elif df.index.tz is None and entry_time.tz is not None:
                entry_time = entry_time.tz_convert(None)

            # Find nearest preceding index in df
            if entry_time in df.index:
                ts_match = entry_time
            else:
                idx_pos = df.index.get_indexer([entry_time], method="pad")[0]
                if idx_pos == -1:
                    continue
                ts_match = df.index[idx_pos]

            if ts_match in test_timestamps:
                original_test_trades.append(trade)
                conf = prob_lookup.get(ts_match, 0.0)

                # Check confidence threshold
                if conf >= self.confidence_threshold:
                    # Append the confidence metric to the trade dict
                    filtered_trade = trade.copy()
                    filtered_trade["ml_confidence"] = float(conf)
                    hybrid_test_trades.append(filtered_trade)

        # 7. Compare performance metrics of test subset
        metrics_comparison = self._evaluate_filtered_trades(
            original_trades=original_test_trades,
            hybrid_trades=hybrid_test_trades,
            df=df,
            strategy_id=strategy_id,
        )

        # 8. Run explainability
        run_output_dir = os.path.join(
            self.config.get("output", {}).get("base_dir", "./data/runs"), run_id, "ml"
        )
        explain_dir = os.path.join(
            run_output_dir, "explainability", f"hybrid_{strategy_id}_{model_name}"
        )
        logger.info(f"Generating explainer charts in {explain_dir}...")
        self.explainer.generate_explainability_report(adapter, X_test, y_test, explain_dir)

        # 9. Register model
        model_registry_dir = os.path.join(run_output_dir, "models")
        self.registry.base_dir = model_registry_dir
        self.registry.save_model(
            model_name=f"hybrid_{strategy_id}_{model_name}",
            adapter=adapter,
            version=version,
            config=self.config,
            validation_metrics={
                "ml_classification": ml_metrics,
                "portfolio_improvement": metrics_comparison,
            },
        )

        return metrics_comparison

    def _evaluate_filtered_trades(
        self,
        original_trades: list[dict[str, Any]],
        hybrid_trades: list[dict[str, Any]],
        df: pd.DataFrame,
        strategy_id: str,
    ) -> dict[str, Any]:
        """Compare backtesting performance metrics between original trades and ML-filtered trades."""
        initial_capital = 100000.0

        # Helper to compute core portfolio metrics from trades list
        def compute_subset_metrics(
            subset_trades: list[dict[str, Any]], trades_label: str
        ) -> dict[str, Any]:
            if not subset_trades:
                return {
                    "total_trades": 0,
                    "net_profit_pct": 0.0,
                    "win_rate": 0.0,
                    "profit_factor": 0.0,
                    "sharpe": 0.0,
                }

            pnls = np.array([float(t.get("pnl_pct", 0.0)) for t in subset_trades])
            net_profit_pct = float(np.sum(pnls))
            wins = np.sum(pnls > 0)
            losses = np.sum(pnls <= 0)
            win_rate = float(wins / len(pnls))

            gross_profit = float(np.sum(pnls[pnls > 0]))
            gross_loss = float(np.abs(np.sum(pnls[pnls <= 0])))
            profit_factor = gross_profit / gross_loss if gross_loss > 0 else float("inf")

            # Sharpe of trade returns (standard quick calculation)
            std_pnl = np.std(pnls)
            mean_pnl = np.mean(pnls)
            sharpe = (mean_pnl / std_pnl * np.sqrt(252)) if std_pnl > 0 else 0.0

            return {
                "total_trades": len(subset_trades),
                "net_profit_pct": round(net_profit_pct, 2),
                "win_rate": round(win_rate * 100, 2),
                "profit_factor": round(profit_factor, 2)
                if profit_factor != float("inf")
                else 999.0,
                "sharpe": round(sharpe, 2),
            }

        orig_metrics = compute_subset_metrics(original_trades, "Original")
        hyb_metrics = compute_subset_metrics(hybrid_trades, "Hybrid")

        # Compute improvements
        trade_reduction_pct = 0.0
        if orig_metrics["total_trades"] > 0:
            trade_reduction_pct = (
                (orig_metrics["total_trades"] - hyb_metrics["total_trades"])
                / orig_metrics["total_trades"]
                * 100
            )

        sharpe_diff = hyb_metrics["sharpe"] - orig_metrics["sharpe"]

        comparison = {
            "strategy_id": strategy_id,
            "original": orig_metrics,
            "hybrid": hyb_metrics,
            "comparison": {
                "trade_reduction_pct": round(trade_reduction_pct, 2),
                "sharpe_improvement": round(sharpe_diff, 2),
                "win_rate_improvement": round(
                    hyb_metrics["win_rate"] - orig_metrics["win_rate"], 2
                ),
                "profit_factor_improvement": round(
                    hyb_metrics["profit_factor"] - orig_metrics["profit_factor"], 2
                ),
            },
        }

        logger.info(
            f"Hybrid Result for {strategy_id} (OOS Test Window): "
            f"Trades: {orig_metrics['total_trades']} -> {hyb_metrics['total_trades']} (-{trade_reduction_pct:.1f}%), "
            f"Sharpe: {orig_metrics['sharpe']:.2f} -> {hyb_metrics['sharpe']:.2f} (+{sharpe_diff:+.2f}), "
            f"Win Rate: {orig_metrics['win_rate']:.1f}% -> {hyb_metrics['win_rate']:.1f}%"
        )
        return comparison
